// This file is generated by generate-std.joke script. Do not edit manually!

package jit

import (
	. "github.com/rcarmo/go-joker/v42/core"
	_ "github.com/rcarmo/go-joker/v42/core/types/collections"
	coretypes "github.com/rcarmo/go-joker/v42/core/types"
)


var __buffer_get__P ProcFn = __buffer_get_
var buffer_get_ Proc = Proc{Fn: __buffer_get__P, Name: "buffer_get_", Package: "std/jit"}

func __buffer_get_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 2:
		buffer := coretypes.ExtractObject(_args, 0)
		index := coretypes.ExtractObject(_args, 1)
		_res := bufferGet(buffer, index)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __buffer_set__P ProcFn = __buffer_set_
var buffer_set_ Proc = Proc{Fn: __buffer_set__P, Name: "buffer_set_", Package: "std/jit"}

func __buffer_set_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 3:
		buffer := coretypes.ExtractObject(_args, 0)
		index := coretypes.ExtractObject(_args, 1)
		value := coretypes.ExtractObject(_args, 2)
		_res := bufferSet(buffer, index, value)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __compile__P ProcFn = __compile_
var compile_ Proc = Proc{Fn: __compile__P, Name: "compile_", Package: "std/jit"}

func __compile_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 1:
		fn := coretypes.ExtractObject(_args, 0)
		_res := compile(ensureJitFn(fn, "jit compile"))
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __compile_wasm__P ProcFn = __compile_wasm_
var compile_wasm_ Proc = Proc{Fn: __compile_wasm__P, Name: "compile_wasm_", Package: "std/jit"}

func __compile_wasm_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 1:
		fn := coretypes.ExtractObject(_args, 0)
		_res := compileWASM(ensureJitFn(fn, "jit compile-wasm"))
		return _res

	case _c == 2:
		fn := coretypes.ExtractObject(_args, 0)
		options := coretypes.ExtractObject(_args, 1)
		_res := compileWASMOptions(ensureJitFn(fn, "jit compile-wasm"), options)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __iscompiled__P ProcFn = __iscompiled_
var iscompiled_ Proc = Proc{Fn: __iscompiled__P, Name: "iscompiled_", Package: "std/jit"}

func __iscompiled_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 1:
		fn := coretypes.ExtractObject(_args, 0)
		_res := coretypes.MakeBoolean(isCompiled(ensureJitFn(fn, "jit compiled?")))
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __export_ir__P ProcFn = __export_ir_
var export_ir_ Proc = Proc{Fn: __export_ir__P, Name: "export_ir_", Package: "std/jit"}

func __export_ir_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 2:
		fn := coretypes.ExtractObject(_args, 0)
		path := coretypes.ExtractString(_args, 1)
		_res := exportIR(ensureJitFn(fn, "jit export-ir"), coretypes.MakeString(path))
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __export_wasm__P ProcFn = __export_wasm_
var export_wasm_ Proc = Proc{Fn: __export_wasm__P, Name: "export_wasm_", Package: "std/jit"}

func __export_wasm_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 2:
		fn := coretypes.ExtractObject(_args, 0)
		path := coretypes.ExtractString(_args, 1)
		_res := exportWASM(ensureJitFn(fn, "jit export-wasm"), coretypes.MakeString(path))
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __info__P ProcFn = __info_
var info_ Proc = Proc{Fn: __info__P, Name: "info_", Package: "std/jit"}

func __info_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 1:
		fn := coretypes.ExtractObject(_args, 0)
		_res := info(ensureJitFn(fn, "jit info"))
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __numeric_buffer__P ProcFn = __numeric_buffer_
var numeric_buffer_ Proc = Proc{Fn: __numeric_buffer__P, Name: "numeric_buffer_", Package: "std/jit"}

func __numeric_buffer_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 1:
		size := coretypes.ExtractObject(_args, 0)
		_res := numericBuffer(size)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var jitNamespace = GLOBAL_ENV.EnsureSymbolIsLib(coretypes.MakeSymbol(STRINGS.Intern, "joker.jit"))

func init() {
	jitNamespace.Lazy = Init
}
