// This file is generated by generate-std.joke script. Do not edit manually!


package jit

import (
	. "github.com/rcarmo/go-joker/v42/core"
	coretypes "github.com/rcarmo/go-joker/v42/core/types"
	corecollections "github.com/rcarmo/go-joker/v42/core/types/collections"
	"fmt"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of jit.InternsOrThunks().")
	}
	jitNamespace.ResetMeta(MakeMeta(nil, `JIT compilation for Clojure functions. Compiles pure arithmetic functions to native Go closures for maximum performance.`, "1.0"))

	
	jitNamespace.InternVar("buffer-get", buffer_get_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "buffer"), coretypes.MakeSymbol(STRINGS.Intern, "index"))),
			`Read one f64 buffer element. The index must be finite, integral and in bounds.`, "42.12.3"))

	jitNamespace.InternVar("buffer-set!", buffer_set_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "buffer"), coretypes.MakeSymbol(STRINGS.Intern, "index"), coretypes.MakeSymbol(STRINGS.Intern, "value"))),
			`Write and return one f64 buffer element. Checks the index and rejects integers outside +/-2^53.`, "42.12.3"))

	jitNamespace.InternVar("compile", compile_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "fn"))),
			`Compiles a function to the fastest available execution path.
  For pure arithmetic fns, returns a native Go f64 closure.
  For other fns, returns an IR-compiled wrapper.`, "1.0"))

	jitNamespace.InternVar("compile-wasm", compile_wasm_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "fn")), corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "fn"), coretypes.MakeSymbol(STRINGS.Intern, "options"))),
			`Compile a numeric function to WASM. Optional {:buffers [argument-indices]} selects checked f64 buffers and nested loops. Dense kernels return Double, reject integers outside +/-2^53, and never replay after a trap. Without options the existing scalar compiler is unchanged.`, "1.0"))

	jitNamespace.InternVar("compiled?", iscompiled_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "fn"))),
			`Returns true if the function can be compiled to IR.`, "1.0"))

	jitNamespace.InternVar("export-ir", export_ir_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "fn"), coretypes.MakeSymbol(STRINGS.Intern, "path"))),
			`Compiles fn to Joker IR and writes a portable .ir JSON file to path.

  The file contains format/version metadata, numSlots, base64-encoded IR
  bytecode, serialized literal constants, and WASM eligibility metadata. It is
  intended for external runners/tooling that implement the go-joker IR ABI.`, "1.0"))

	jitNamespace.InternVar("export-wasm", export_wasm_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "fn"), coretypes.MakeSymbol(STRINGS.Intern, "path"))),
			`Compiles fn to a standalone numeric WASM module and writes raw .wasm bytes.

  The exported module exposes an ` + "`" + `exec` + "`" + ` function. Parameters and return values
  are i64 for integer IR programs or f64 for floating-point IR programs. Only
  pure WASM-eligible IR shapes can be exported this way; functions requiring
  Joker object/collection host imports should use export-ir instead.`, "1.0"))

	jitNamespace.InternVar("info", info_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "fn"))),
			`Returns a map with compilation information about a function.
  Keys: :compiled, :path, :slots, :captures, :self-recursive.`, "1.0"))

	jitNamespace.InternVar("numeric-buffer", numeric_buffer_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "size"))),
			`Allocate a checked f64 buffer of 0..1048576 elements for dense WASM kernels.`, "42.12.3"))

}
