#!/usr/bin/env bash
set -euo pipefail

root=${1:-.}
cd "$root"

missing=0
manifest=tests/generated_files.txt
if [[ ! -f "$manifest" ]]; then
  echo "generated guard: missing manifest: $manifest" >&2
  missing=1
elif ! diff -u "$manifest" <(
  {
    find core -maxdepth 1 -type f \( -name 'a_*.go' -o -name 'types_*_gen.go' \);
    find core/generated -maxdepth 1 -type f -name 'a_linter_*_data.go';
  } | sort
); then
  echo "generated guard: generated file set changed; update $manifest intentionally" >&2
  missing=1
fi

while IFS= read -r file; do
  if ! head -n 1 "$file" | grep -q 'Generated by gen_code\|Generated by gen_types\|Code generated'; then
    echo "generated guard: missing generated banner: $file" >&2
    missing=1
  fi
  if grep -n "TODO\|FIXME" "$file" >/dev/null; then
    echo "generated guard: generated file contains TODO/FIXME: $file" >&2
    missing=1
  fi
done < <(
  {
    find core -maxdepth 1 -type f \( -name 'a_*.go' -o -name 'types_*_gen.go' \);
    find core/generated -maxdepth 1 -type f -name 'a_linter_*_data.go';
  } | sort
)

for dir in core/gen core/gen_code core/gen_go core/generated; do
  test -d "$dir" || { echo "generated guard: missing generator directory: $dir" >&2; missing=1; }
done

if [[ ! -f core/generated/core_sources_gen.go ]]; then
  echo "generated guard: missing generated bootstrap source manifest" >&2
  missing=1
elif ! head -n 1 core/generated/core_sources_gen.go | grep -q 'Generated by gen_code'; then
  echo "generated guard: bootstrap source manifest missing generated banner" >&2
  missing=1
fi

if ! tests/generated_source_manifest_guard.py .; then
  missing=1
fi

exit "$missing"
