#!/usr/bin/env bash
set -euo pipefail

root=${1:-.}
cd "$root"

missing=0
while IFS= read -r file; do
  if ! head -n 1 "$file" | grep -q 'Generated by gen_code\|Generated by gen_types\|Code generated'; then
    echo "generated guard: missing generated banner: $file" >&2
    missing=1
  fi
  if grep -n "TODO\|FIXME" "$file" >/dev/null; then
    echo "generated guard: generated file contains TODO/FIXME: $file" >&2
    missing=1
  fi
done < <(find core -maxdepth 1 -type f \( -name 'a_*.go' -o -name 'types_*_gen.go' \) | sort)

for dir in core/gen core/gen_code core/gen_go; do
  test -d "$dir" || { echo "generated guard: missing generator directory: $dir" >&2; missing=1; }
done

exit "$missing"
