// This file is generated by generate-std.joke script. Do not edit manually!

package http

import (
	"fmt"
	. "github.com/rcarmo/go-joker/core"
	coretypes "github.com/rcarmo/go-joker/core/types"
	"os"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of http.InternsOrThunks().")
	}
	httpNamespace.ResetMeta(MakeMeta(nil, `Provides HTTP client and server implementations.`, "1.0"))

	httpNamespace.InternVar("send", send_,
		MakeMeta(
			NewListFrom(NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "request"))),
			`Sends an HTTP request and returns an HTTP response.
  request is a map with the following keys:
  - url (string)
  - method (string, keyword or symbol, defaults to :get)
  - body (string)
  - host (string, overrides Host header if provided)
  - headers (map).
  All keys except for url are optional.
  response is a map with the following keys:
  - status (int)
  - body (string)
  - headers (map)
  - content-length (int, or BigInt when it exceeds the native int range)`, "1.0"))

	httpNamespace.InternVar("start-file-server", start_file_server_,
		MakeMeta(
			NewListFrom(NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "addr"), coretypes.MakeSymbol(STRINGS.Intern, "root"))),
			`Starts HTTP server on the TCP network address addr that
  serves HTTP requests with the contents of the file system rooted at root.`, "1.0"))

	httpNamespace.InternVar("start-server", start_server_,
		MakeMeta(
			NewListFrom(NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "addr"), coretypes.MakeSymbol(STRINGS.Intern, "handler"))),
			`Starts an HTTP server on the TCP network address addr.

  handler is called as (handler request-map) and should return a response map.

  Standard HTTP response map:
    {:status 200
     :headers {'Content-Type' 'text/plain'}
     :body 'Hello'}

  Request map keys include:
    :request-method :uri :query-string :body :headers
    :server-name :server-port :remote-addr :protocol :scheme :host

  WebSocket upgrade extension (response key :websocket):
    {:websocket
      {:on-open    (fn [send close] ...)
       :on-message (fn [msg] ...)
       :on-close   (fn [] ...)}}

    send is (fn [msg]) and sends a text frame.
    close is (fn []) and closes the connection.

  SSE/chunked streaming extension (response key :stream):
    {:status 200
     :headers {'Cache-Control' 'no-cache'}
     :stream (fn [send-event]
               (send-event 'tick')
               (send-event 'complete' 'done'))}

    send-event supports:
      (send-event data)
      (send-event event data)

  Header values can be strings or seqs of strings.`, "1.0"))

}
