// This file is generated by generate-std.joke script. Do not edit manually!

package http

import (
	"fmt"
	"os"

	. "github.com/rcarmo/go-joker/core"
	coretypes "github.com/rcarmo/go-joker/core/types"
	corecollections "github.com/rcarmo/go-joker/core/types/collections"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of http.InternsOrThunks().")
	}
	httpNamespace.ResetMeta(MakeMeta(nil, `Provides HTTP client and server implementations.`, "1.0"))

	httpNamespace.InternVar("client", client_,
		MakeMeta(
			corecollections.NewListFrom(
				corecollections.NewVectorFrom(),
				corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "opts"))),
			`Creates a high-performance persistent HTTP client.

  Options map keys:
  - :max-idle-conns (default 100)
  - :max-idle-conns-per-host (default 100)
  - :idle-timeout-ms (default 90000)`, "1.0"))

	httpNamespace.InternVar("close-client", close_client_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "c"))),
			`Closes idle keep-alive connections for a client created by joker.http/client.`, "1.0"))

	httpNamespace.InternVar("send", send_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "request"))),
			`Sends an HTTP request and returns an HTTP response.
  request is a map with the following keys:
  - url (string)
  - method (string, keyword or symbol, defaults to :get)
  - body (string)
  - host (string, overrides Host header if provided)
  - headers (map)
  - client (persistent client from joker.http/client)
  - timeout-ms (optional per-request deadline).
  All keys except for url are optional.
  response is a map with the following keys:
  - status (int)
  - body (string)
  - headers (map)
  - content-length (int, or BigInt when it exceeds the native int range)`, "1.0"))

	httpNamespace.InternVar("send-sse", send_sse_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "request"), coretypes.MakeSymbol(STRINGS.Intern, "callback"))),
			`Sends an HTTP request and incrementally parses a text/event-stream response.

  Calls callback with {:event string :data string} for each SSE event. :id and
  :retry are included when present. Returning false from callback cancels the
  response body. Supports :timeout-ms and :max-event-bytes request options.
  Non-2xx responses are returned with a bounded :body.`, "1.0"))

	httpNamespace.InternVar("start-file-server", start_file_server_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "addr"), coretypes.MakeSymbol(STRINGS.Intern, "root"))),
			`Starts HTTP server on the TCP network address addr that
  serves HTTP requests with the contents of the file system rooted at root.`, "1.0"))

	httpNamespace.InternVar("start-server", start_server_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "addr"), coretypes.MakeSymbol(STRINGS.Intern, "handler"))),
			`Starts an HTTP server on the TCP network address addr.

  handler is called as (handler request-map) and should return a response map.

  Standard HTTP response map:
    {:status 200
     :headers {'Content-Type' 'text/plain'}
     :body 'Hello'}

  Request map keys include:
    :request-method :uri :query-string :body :headers
    :server-name :server-port :remote-addr :protocol :scheme :host

  WebSocket upgrade extension (response key :websocket):
    {:websocket
      {:on-open    (fn [send close] ...)
       :on-message (fn [msg] ...)
       :on-close   (fn [] ...)}}

    send is (fn [msg]) and sends a text frame.
    close is (fn []) and closes the connection.

  SSE/chunked streaming extension (response key :stream):
    {:status 200
     :headers {'Cache-Control' 'no-cache'}
     :stream (fn [send-event]
               (send-event 'tick')
               (send-event 'complete' 'done'))}

    send-event supports:
      (send-event data)
      (send-event event data)

  Header values can be strings or seqs of strings.`, "1.0"))

}
