// This file is generated by generate-std.joke script. Do not edit manually!

package http

import (
	. "github.com/rcarmo/go-joker/core"
	coretypes "github.com/rcarmo/go-joker/core/types"
)

var __client__P ProcFn = __client_
var client_ Proc = Proc{Fn: __client__P, Name: "client_", Package: "std/http"}

func __client_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 0:
		return makeClient(nil)
	case _c == 1:
		return makeClient([]coretypes.Object{coretypes.ExtractMap(_args, 0)})
	default:
		PanicArity(_c)
	}
	return NIL
}

var __close_client__P ProcFn = __close_client_
var close_client_ Proc = Proc{Fn: __close_client__P, Name: "close_client_", Package: "std/http"}

func __close_client_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	if _c == 1 {
		return closeClient(_args[0])
	}
	PanicArity(_c)
	return NIL
}

var __send__P ProcFn = __send_
var send_ Proc = Proc{Fn: __send__P, Name: "send_", Package: "std/http"}

func __send_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 1:
		request := coretypes.ExtractMap(_args, 0)
		_res := sendRequest(request)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __send_sse__P ProcFn = __send_sse_
var send_sse_ Proc = Proc{Fn: __send_sse__P, Name: "send_sse_", Package: "std/http"}

func __send_sse_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 2:
		request := coretypes.ExtractMap(_args, 0)
		callback := coretypes.ExtractCallable(_args, 1)
		return sendSSE(request, callback)
	default:
		PanicArity(_c)
	}
	return NIL
}

var __start_file_server__P ProcFn = __start_file_server_
var start_file_server_ Proc = Proc{Fn: __start_file_server__P, Name: "start_file_server_", Package: "std/http"}

func __start_file_server_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 2:
		addr := coretypes.ExtractString(_args, 0)
		root := coretypes.ExtractString(_args, 1)
		_res := startFileServer(addr, root)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

var __start_server__P ProcFn = __start_server_
var start_server_ Proc = Proc{Fn: __start_server__P, Name: "start_server_", Package: "std/http"}

func __start_server_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 2:
		addr := coretypes.ExtractString(_args, 0)
		handler := coretypes.ExtractCallable(_args, 1)
		_res := startServer(addr, handler)
		return _res

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var httpNamespace = GLOBAL_ENV.EnsureSymbolIsLib(coretypes.MakeSymbol(STRINGS.Intern, "joker.http"))

func init() {
	httpNamespace.Lazy = Init
}
