// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

func init() {
	ns_joker_DOT_better_DASH_cond.Lazy = better_condLazyInit

}

func better_condLazyInit() {
	bitmapIndexedNode_NUM_232.array[9] = &ns_joker_DOT_better_DASH_cond
	bitmapIndexedNode_NUM_234.array[9] = &ns_joker_DOT_better_DASH_cond
	bitmapIndexedNode_NUM_236.array[9] = &ns_joker_DOT_better_DASH_cond
	bitmapIndexedNode_NUM_238.array[9] = &ns_joker_DOT_better_DASH_cond
	bitmapIndexedNode_NUM_240.array[9] = &ns_joker_DOT_better_DASH_cond
	var_NAME_cond_POS_joker_DOT_better_DASH_cond_57_1__82_13.ns = &ns_joker_DOT_better_DASH_cond
	var_NAME_if_DASH_let_POS_joker_DOT_better_DASH_cond_7_1__23_12.ns = &ns_joker_DOT_better_DASH_cond
	var_NAME_if_DASH_some_POS_joker_DOT_better_DASH_cond_32_1__48_12.ns = &ns_joker_DOT_better_DASH_cond
	var_NAME_when_DASH_let_POS_joker_DOT_better_DASH_cond_25_1__30_34.ns = &ns_joker_DOT_better_DASH_cond
	var_NAME_when_DASH_some_POS_joker_DOT_better_DASH_cond_50_1__55_35.ns = &ns_joker_DOT_better_DASH_cond
}
