// Generated by gen_code. Don't modify manually!

package core

func init() {
	coreNamespaces = []string{
		"joker.better-cond",
		"joker.core",
		"joker.hiccup",
		"joker.pprint",
		"joker.repl",
		"joker.set",
		"joker.template",
		"joker.test",
		"joker.tools.cli",
		"joker.walk",
		"user",
	}
}
