// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

import (
	"regexp"
)

func init() {
	ns_joker_DOT_hiccup.Lazy = hiccupLazyInit

}

func hiccupLazyInit() {
	arrayMap_NUM_1363.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1364.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1365.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1366.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1367.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1369.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1370.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1371.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1372.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1373.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1374.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1375.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1376.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1377.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1378.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1379.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1380.arr[7] = &ns_joker_DOT_hiccup
	arrayMap_NUM_1381.arr[7] = &ns_joker_DOT_hiccup
	var_NAME_as_DASH_str_POS_joker_DOT_hiccup_16_1__29_13.ns = &ns_joker_DOT_hiccup
	var_NAME_container_DASH_tag_Q__POS_joker_DOT_hiccup_78_1__81_53.ns = &ns_joker_DOT_hiccup
	var_NAME_end_DASH_tag_POS_joker_DOT_hiccup_39_1__41_34.ns = &ns_joker_DOT_hiccup
	var_NAME_escape_DASH_html_POS_joker_DOT_hiccup_43_1__45_23.ns = &ns_joker_DOT_hiccup
	var_NAME_html_DASH_mode_Q__POS_joker_DOT_hiccup_35_1__37_25.ns = &ns_joker_DOT_hiccup
	var_NAME_html_POS_joker_DOT_hiccup_152_1__166_35.ns = &ns_joker_DOT_hiccup
	var_NAME_merge_DASH_attributes_POS_joker_DOT_hiccup_83_1__86_77.ns = &ns_joker_DOT_hiccup
	var_NAME_named_Q__POS_joker_DOT_hiccup_10_1__14_19.ns = &ns_joker_DOT_hiccup
	var_NAME_normalize_DASH_element_POS_joker_DOT_hiccup_91_1__102_32.ns = &ns_joker_DOT_hiccup
	var_NAME_raw_DASH_string_POS_joker_DOT_hiccup_145_1__150_25.ns = &ns_joker_DOT_hiccup
	var_NAME_re_DASH_tag_POS_joker_DOT_hiccup_89_1__89_70.ns = &ns_joker_DOT_hiccup
	var_NAME_render_DASH_attr_DASH_map_POS_joker_DOT_hiccup_65_1__71_17.ns = &ns_joker_DOT_hiccup
	var_NAME_render_DASH_attribute_POS_joker_DOT_hiccup_51_1__63_32.ns = &ns_joker_DOT_hiccup
	var_NAME_render_DASH_element_POS_joker_DOT_hiccup_131_1__143_57.ns = &ns_joker_DOT_hiccup
	var_NAME_render_DASH_markup_POS_joker_DOT_hiccup_106_1__129_27.ns = &ns_joker_DOT_hiccup
	var_NAME_void_DASH_tags_POS_joker_DOT_hiccup_73_1__76_43.ns = &ns_joker_DOT_hiccup
	var_NAME_xml_DASH_attribute_POS_joker_DOT_hiccup_47_1__49_56.ns = &ns_joker_DOT_hiccup
	var_NAME_xml_DASH_mode_Q__POS_joker_DOT_hiccup_31_1__33_24.ns = &ns_joker_DOT_hiccup
	varRef_render_DASH_markup_POS_joker_DOT_hiccup__121_17__121_29.vr = &var_NAME_render_DASH_markup_POS_joker_DOT_hiccup_106_1__129_27
	varRef_render_DASH_markup_POS_joker_DOT_hiccup__138_29__138_41.vr = &var_NAME_render_DASH_markup_POS_joker_DOT_hiccup_106_1__129_27
	regex_POS_joker_DOT_hiccup__89_23__89_69_NUM_1.R = regexp.MustCompile("([^\\s\\.#]+)(?:#([^\\s\\.#]+))?(?:\\.([^\\s#]+))?")
	ns_joker_DOT_html.MaybeLazy("joker.hiccup")
	ns_joker_DOT_string.MaybeLazy("joker.hiccup")
}
