// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

import ()

func init() {
	ns_joker_DOT_pprint.Lazy = pprintLazyInit

}

func pprintLazyInit() {
	arrayMap_NUM_1383.arr[7] = &ns_joker_DOT_pprint
	var_NAME_print_DASH_table_POS_joker_DOT_pprint_5_1__29_50.ns = &ns_joker_DOT_pprint
	varRef_print_DASH_table_POS_joker_DOT_pprint__29_12__29_22.vr = &var_NAME_print_DASH_table_POS_joker_DOT_pprint_5_1__29_50
}
