// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

func init() {
	ns_joker_DOT_repl.Lazy = replLazyInit

}

func replLazyInit() {
	arrayMap_NUM_1272.arr[7] = &ns_joker_DOT_repl
	arrayMap_NUM_1273.arr[7] = &ns_joker_DOT_repl
	arrayMap_NUM_1274.arr[7] = &ns_joker_DOT_repl
	arrayMap_NUM_1275.arr[7] = &ns_joker_DOT_repl
	arrayMap_NUM_1276.arr[7] = &ns_joker_DOT_repl
	arrayMap_NUM_1277.arr[7] = &ns_joker_DOT_repl
	bitmapIndexedNode_NUM_187.array[9] = &ns_joker_DOT_repl
	bitmapIndexedNode_NUM_189.array[9] = &ns_joker_DOT_repl
	var_NAME_apropos_POS_joker_DOT_repl_94_1__107_30.ns = &ns_joker_DOT_repl
	var_NAME_dir_DASH_fn_POS_joker_DOT_repl_109_1__114_73.ns = &ns_joker_DOT_repl
	var_NAME_dir_POS_joker_DOT_repl_116_1__121_19.ns = &ns_joker_DOT_repl
	var_NAME_doc_POS_joker_DOT_repl_74_1__89_52.ns = &ns_joker_DOT_repl
	var_NAME_namespace_DASH_doc_POS_joker_DOT_repl_44_1__45_47.ns = &ns_joker_DOT_repl
	var_NAME_print_DASH_doc_POS_joker_DOT_repl_47_1__72_31.ns = &ns_joker_DOT_repl
	var_NAME_special_DASH_doc_DASH_map_POS_joker_DOT_repl_6_1__37_82.ns = &ns_joker_DOT_repl
	var_NAME_special_DASH_doc_POS_joker_DOT_repl_39_1__42_29.ns = &ns_joker_DOT_repl
	ns_joker_DOT_string.MaybeLazy("joker.repl")
}
