// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

import ()

func init() {
	ns_joker_DOT_set.Lazy = setLazyInit

}

func setLazyInit() {
	arrayMap_NUM_1324.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1325.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1326.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1327.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1328.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1329.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1330.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1331.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1332.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1333.arr[7] = &ns_joker_DOT_set
	arrayMap_NUM_1334.arr[7] = &ns_joker_DOT_set
	bitmapIndexedNode_NUM_228.array[7] = &ns_joker_DOT_set
	bitmapIndexedNode_NUM_230.array[7] = &ns_joker_DOT_set
	var_NAME_bubble_DASH_max_DASH_key_POS_joker_DOT_set_14_1__19_50.ns = &ns_joker_DOT_set
	var_NAME_difference_POS_joker_DOT_set_50_1__63_44.ns = &ns_joker_DOT_set
	var_NAME_index_POS_joker_DOT_set_96_1__105_14.ns = &ns_joker_DOT_set
	var_NAME_intersection_POS_joker_DOT_set_34_1__48_72.ns = &ns_joker_DOT_set
	var_NAME_join_POS_joker_DOT_set_112_1__141_22.ns = &ns_joker_DOT_set
	var_NAME_map_DASH_invert_POS_joker_DOT_set_107_1__110_49.ns = &ns_joker_DOT_set
	var_NAME_project_POS_joker_DOT_set_73_1__77_63.ns = &ns_joker_DOT_set
	var_NAME_rename_DASH_keys_POS_joker_DOT_set_79_1__88_42.ns = &ns_joker_DOT_set
	var_NAME_rename_POS_joker_DOT_set_90_1__94_65.ns = &ns_joker_DOT_set
	var_NAME_select_POS_joker_DOT_set_66_1__71_23.ns = &ns_joker_DOT_set
	var_NAME_subset_Q__POS_joker_DOT_set_143_1__149_42.ns = &ns_joker_DOT_set
	var_NAME_superset_Q__POS_joker_DOT_set_151_1__157_42.ns = &ns_joker_DOT_set
	var_NAME_union_POS_joker_DOT_set_21_1__32_64.ns = &ns_joker_DOT_set
	varRef_difference_POS_joker_DOT_set__63_14__63_23.vr = &var_NAME_difference_POS_joker_DOT_set_50_1__63_44
	varRef_intersection_POS_joker_DOT_set__48_16__48_27.vr = &var_NAME_intersection_POS_joker_DOT_set_34_1__48_72
}
