// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

func init() {
	ns_joker_DOT_template.Lazy = templateLazyInit

}

func templateLazyInit() {
	arrayMap_NUM_1290.arr[7] = &ns_joker_DOT_template
	bitmapIndexedNode_NUM_192.array[9] = &ns_joker_DOT_template
	var_NAME_apply_DASH_template_POS_joker_DOT_template_31_1__45_52.ns = &ns_joker_DOT_template
	var_NAME_do_DASH_template_POS_joker_DOT_template_47_1__58_40.ns = &ns_joker_DOT_template
	ns_joker_DOT_walk.MaybeLazy("joker.template")
}
