// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

import ()

func init() {
	ns_joker_DOT_test.Lazy = testLazyInit

}

func testLazyInit() {
	localEnv_NUM_18.bindings[0] = &fn_EMPTY_POS_joker_DOT_core_4340_7__4350_31_NUM_1
	localEnv_NUM_24.bindings[0] = &fn_EMPTY_POS_joker_DOT_core_4340_7__4350_31_NUM_3
	arrayMap_NUM_1292.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1294.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1295.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1296.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1297.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1298.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1299.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1302.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1303.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1304.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1305.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1306.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1307.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1309.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1310.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1311.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1312.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1313.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1314.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1315.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1316.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1317.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1318.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1319.arr[7] = &ns_joker_DOT_test
	arrayMap_NUM_1320.arr[7] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_194.array[7] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_196.array[7] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_198.array[7] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_201.array[9] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_203.array[7] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_206.array[9] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_208.array[9] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_213.array[9] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_215.array[7] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_218.array[9] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_220.array[9] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_222.array[9] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_224.array[9] = &ns_joker_DOT_test
	bitmapIndexedNode_NUM_226.array[9] = &ns_joker_DOT_test
	var_NAME__STAR_initial_DASH_report_DASH_counters_STAR__POS_joker_DOT_test_262_1__266_66.ns = &ns_joker_DOT_test
	var_NAME__STAR_load_DASH_tests_STAR__POS_joker_DOT_test_238_1__243_20.ns = &ns_joker_DOT_test
	var_NAME__STAR_report_DASH_counters_STAR__POS_joker_DOT_test_256_1__260_24.ns = &ns_joker_DOT_test
	var_NAME__STAR_stack_DASH_trace_DASH_depth_STAR__POS_joker_DOT_test_245_1__251_26.ns = &ns_joker_DOT_test
	var_NAME__STAR_test_DASH_out_STAR__POS_joker_DOT_test_278_1__281_19.ns = &ns_joker_DOT_test
	var_NAME__STAR_testing_DASH_contexts_STAR__POS_joker_DOT_test_273_1__276_28.ns = &ns_joker_DOT_test
	var_NAME__STAR_testing_DASH_vars_STAR__POS_joker_DOT_test_268_1__271_24.ns = &ns_joker_DOT_test
	var_NAME_add_DASH_ns_DASH_meta_POS_joker_DOT_test_655_1__660_36.ns = &ns_joker_DOT_test
	var_NAME_are_POS_joker_DOT_test_564_1__587_108.ns = &ns_joker_DOT_test
	var_NAME_assert_DASH_any_POS_joker_DOT_test_445_1__456_13.ns = &ns_joker_DOT_test
	var_NAME_assert_DASH_expr_POS_joker_DOT_test_466_1__473_23.ns = &ns_joker_DOT_test
	var_NAME_assert_DASH_predicate_POS_joker_DOT_test_426_1__443_17.ns = &ns_joker_DOT_test
	var_NAME_compose_DASH_fixtures_POS_joker_DOT_test_681_1__686_31.ns = &ns_joker_DOT_test
	var_NAME_default_DASH_fixture_POS_joker_DOT_test_675_1__679_6.ns = &ns_joker_DOT_test
	var_NAME_deftest_DASH__POS_joker_DOT_test_631_1__637_40.ns = &ns_joker_DOT_test
	var_NAME_deftest_POS_joker_DOT_test_614_1__629_40.ns = &ns_joker_DOT_test
	var_NAME_do_DASH_report_POS_joker_DOT_test_341_1__357_6.ns = &ns_joker_DOT_test
	var_NAME_function_Q__POS_joker_DOT_test_414_1__424_13.ns = &ns_joker_DOT_test
	var_NAME_get_DASH_possibly_DASH_unbound_DASH_var_POS_joker_DOT_test_406_1__412_15.ns = &ns_joker_DOT_test
	var_NAME_inc_DASH_report_DASH_counter_POS_joker_DOT_test_312_1__318_74.ns = &ns_joker_DOT_test
	var_NAME_is_POS_joker_DOT_test_546_1__562_38.ns = &ns_joker_DOT_test
	var_NAME_join_DASH_fixtures_POS_joker_DOT_test_688_1__693_53.ns = &ns_joker_DOT_test
	var_NAME_report_POS_joker_DOT_test_322_1__330_15.ns = &ns_joker_DOT_test
	var_NAME_run_DASH_all_DASH_tests_POS_joker_DOT_test_772_1__779_81.ns = &ns_joker_DOT_test
	var_NAME_run_DASH_tests_POS_joker_DOT_test_760_1__770_15.ns = &ns_joker_DOT_test
	var_NAME_set_DASH_test_POS_joker_DOT_test_640_1__649_59.ns = &ns_joker_DOT_test
	var_NAME_stacktrace_DASH_file_DASH_and_DASH_line_POS_joker_DOT_test_334_1__339_24.ns = &ns_joker_DOT_test
	var_NAME_successful_Q__POS_joker_DOT_test_781_1__787_35.ns = &ns_joker_DOT_test
	var_NAME_test_DASH_all_DASH_vars_POS_joker_DOT_test_729_1__733_37.ns = &ns_joker_DOT_test
	var_NAME_test_DASH_ns_POS_joker_DOT_test_735_1__754_24.ns = &ns_joker_DOT_test
	var_NAME_test_DASH_var_POS_joker_DOT_test_700_1__713_50.ns = &ns_joker_DOT_test
	var_NAME_test_DASH_vars_POS_joker_DOT_test_715_1__727_58.ns = &ns_joker_DOT_test
	var_NAME_testing_DASH_contexts_DASH_str_POS_joker_DOT_test_305_1__310_59.ns = &ns_joker_DOT_test
	var_NAME_testing_DASH_vars_DASH_str_POS_joker_DOT_test_292_1__303_30.ns = &ns_joker_DOT_test
	var_NAME_testing_POS_joker_DOT_test_589_1__595_13.ns = &ns_joker_DOT_test
	var_NAME_try_DASH_expr_POS_joker_DOT_test_530_1__538_55.ns = &ns_joker_DOT_test
	var_NAME_use_DASH_fixtures_POS_joker_DOT_test_662_1__667_42.ns = &ns_joker_DOT_test
	var_NAME_with_DASH_test_DASH_out_POS_joker_DOT_test_283_1__288_13.ns = &ns_joker_DOT_test
	var_NAME_with_DASH_test_POS_joker_DOT_test_601_1__611_16.ns = &ns_joker_DOT_test
	localEnv_NUM_19.bindings[0] = &var_NAME_assert_DASH_expr_POS_joker_DOT_test_466_1__473_23
	varRef_run_DASH_tests_POS_joker_DOT_test__765_8__765_16.vr = &var_NAME_run_DASH_tests_POS_joker_DOT_test_760_1__770_15
	localEnv_NUM_25.bindings[0] = &var_NAME_use_DASH_fixtures_POS_joker_DOT_test_662_1__667_42
	var_NAME__STAR_test_DASH_out_STAR__POS_joker_DOT_test_278_1__281_19.Value = var_NS_joker_DOT_core_NAME__STAR_out_STAR_.Value
}
