// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

import (
	"regexp"
)

func init() {
	ns_joker_DOT_tools_DOT_cli.Lazy = tools_cliLazyInit

}

func tools_cliLazyInit() {
	arrayMap_NUM_1336.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1337.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1338.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1339.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1340.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1341.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1342.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1343.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1344.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1345.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1346.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1347.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1348.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1349.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1350.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1351.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1352.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1353.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1354.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1355.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1356.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1357.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1358.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1359.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1360.arr[7] = &ns_joker_DOT_tools_DOT_cli
	arrayMap_NUM_1361.arr[7] = &ns_joker_DOT_tools_DOT_cli
	var_NAME_compile_DASH_option_DASH_specs_POS_joker_DOT_tools_DOT_cli_117_1__172_21.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_compile_DASH_spec_POS_joker_DOT_tools_DOT_cli_83_1__103_60.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_default_DASH_option_DASH_map_POS_joker_DOT_tools_DOT_cli_174_1__179_20.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_distinct_Q__STAR__POS_joker_DOT_tools_DOT_cli_105_1__108_10.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_find_DASH_spec_POS_joker_DOT_tools_DOT_cli_190_1__200_12.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_format_DASH_lines_POS_joker_DOT_tools_DOT_cli_330_1__337_49.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_get_DASH_default_DASH_options_POS_joker_DOT_tools_DOT_cli_364_1__376_53.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_make_DASH_format_POS_joker_DOT_tools_DOT_cli_56_1__60_70.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_make_DASH_summary_DASH_part_POS_joker_DOT_tools_DOT_cli_306_1__328_27.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_missing_DASH_errors_POS_joker_DOT_tools_DOT_cli_181_1__188_20.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_missing_DASH_required_DASH_error_POS_joker_DOT_tools_DOT_cli_205_1__206_72.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_neg_DASH_flag_Q__POS_joker_DOT_tools_DOT_cli_236_1__239_32.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_parse_DASH_error_POS_joker_DOT_tools_DOT_cli_208_1__209_68.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_parse_DASH_optarg_POS_joker_DOT_tools_DOT_cli_241_1__248_47.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_parse_DASH_option_DASH_tokens_POS_joker_DOT_tools_DOT_cli_250_1__304_30.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_parse_DASH_opts_POS_joker_DOT_tools_DOT_cli_379_1__550_42.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_parse_DASH_value_POS_joker_DOT_tools_DOT_cli_224_1__234_41.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_pr_DASH_join_POS_joker_DOT_tools_DOT_cli_202_1__203_30.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_required_DASH_arguments_POS_joker_DOT_tools_DOT_cli_339_1__345_14.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_select_DASH_spec_DASH_keys_POS_joker_DOT_tools_DOT_cli_70_1__81_30.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_spec_DASH_keys_POS_joker_DOT_tools_DOT_cli_66_1__68_71.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_summarize_POS_joker_DOT_tools_DOT_cli_347_1__362_8.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_tokenize_DASH_args_POS_joker_DOT_tools_DOT_cli_7_1__54_23.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_validate_POS_joker_DOT_tools_DOT_cli_215_1__222_22.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_validation_DASH_error_POS_joker_DOT_tools_DOT_cli_211_1__213_35.ns = &ns_joker_DOT_tools_DOT_cli
	var_NAME_wrap_DASH_val_POS_joker_DOT_tools_DOT_cli_110_1__115_9.ns = &ns_joker_DOT_tools_DOT_cli
	regex_POS_joker_DOT_tools_DOT_cli__30_71__30_74_NUM_1.R = regexp.MustCompile("=")
	regex_POS_joker_DOT_tools_DOT_cli__89_41__89_67_NUM_1.R = regexp.MustCompile("^(--[^ =]+)(?:[ =](.*))?")
	regex_POS_joker_DOT_tools_DOT_cli__33_11__33_16_NUM_1.R = regexp.MustCompile("^--")
	regex_POS_joker_DOT_tools_DOT_cli__28_11__28_17_NUM_1.R = regexp.MustCompile("^--$")
	regex_POS_joker_DOT_tools_DOT_cli__91_37__91_56_NUM_1.R = regexp.MustCompile("^--(\\[no-\\])?(.*)")
	regex_POS_joker_DOT_tools_DOT_cli__30_11__30_20_NUM_1.R = regexp.MustCompile("^--\\S+=")
	regex_POS_joker_DOT_tools_DOT_cli__238_17__238_29_NUM_1.R = regexp.MustCompile("^--\\[no-\\]")
	regex_POS_joker_DOT_tools_DOT_cli__195_42__195_58_NUM_1.R = regexp.MustCompile("^--\\[no-\\](.*)")
	regex_POS_joker_DOT_tools_DOT_cli__239_17__239_25_NUM_1.R = regexp.MustCompile("^--no-")
	regex_POS_joker_DOT_tools_DOT_cli__39_11__39_16_NUM_1.R = regexp.MustCompile("^-.")
	ns_joker_DOT_string.MaybeLazy("joker.tools.cli")
}
