// Generated by gen_code. Don't modify manually!

//go:build !gen_code
// +build !gen_code

package core

func init() {
	ns_joker_DOT_walk.Lazy = walkLazyInit

}

func walkLazyInit() {
	arrayMap_NUM_1279.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1280.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1281.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1282.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1283.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1284.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1285.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1286.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1287.arr[7] = &ns_joker_DOT_walk
	arrayMap_NUM_1288.arr[7] = &ns_joker_DOT_walk
	var_NAME_keywordize_DASH_keys_POS_joker_DOT_walk_97_1__103_63.ns = &ns_joker_DOT_walk
	var_NAME_macroexpand_DASH_all_POS_joker_DOT_walk_129_1__133_58.ns = &ns_joker_DOT_walk
	var_NAME_postwalk_DASH_demo_POS_joker_DOT_walk_83_1__88_56.ns = &ns_joker_DOT_walk
	var_NAME_postwalk_DASH_replace_POS_joker_DOT_walk_121_1__127_62.ns = &ns_joker_DOT_walk
	var_NAME_postwalk_POS_joker_DOT_walk_56_1__62_37.ns = &ns_joker_DOT_walk
	var_NAME_prewalk_DASH_demo_POS_joker_DOT_walk_90_1__95_55.ns = &ns_joker_DOT_walk
	var_NAME_prewalk_DASH_replace_POS_joker_DOT_walk_113_1__119_61.ns = &ns_joker_DOT_walk
	var_NAME_prewalk_POS_joker_DOT_walk_64_1__68_47.ns = &ns_joker_DOT_walk
	var_NAME_stringify_DASH_keys_POS_joker_DOT_walk_105_1__111_63.ns = &ns_joker_DOT_walk
	var_NAME_walk_POS_joker_DOT_walk_36_1__54_24.ns = &ns_joker_DOT_walk
	varRef_postwalk_POS_joker_DOT_walk__62_18__62_25.vr = &var_NAME_postwalk_POS_joker_DOT_walk_56_1__62_37
	varRef_prewalk_POS_joker_DOT_walk__68_18__68_24.vr = &var_NAME_prewalk_POS_joker_DOT_walk_64_1__68_47
}
