// Generated by gen_types. Don't modify manually!

package core

import (
	"io"

	coretypes "github.com/rcarmo/go-joker/core/types"
)

func EnsureObjectIsComparable(obj coretypes.Object, pattern string) coretypes.Comparable {
	if c, yes := obj.(coretypes.Comparable); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Comparable", pattern))
}

func EnsureArgIsComparable(args []coretypes.Object, index int) coretypes.Comparable {
	obj := args[index]
	if c, yes := obj.(coretypes.Comparable); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Comparable", index))
}

func EnsureObjectIsVec(obj coretypes.Object, pattern string) Vec {
	if c, yes := obj.(Vec); yes {
		return c
	}
	panic(FailObject(obj, "Vec", pattern))
}

func EnsureArgIsVec(args []coretypes.Object, index int) Vec {
	obj := args[index]
	if c, yes := obj.(Vec); yes {
		return c
	}
	panic(FailArg(obj, "Vec", index))
}

func EnsureObjectIsChar(obj coretypes.Object, pattern string) coretypes.Char {
	if c, yes := obj.(coretypes.Char); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Char", pattern))
}

func EnsureArgIsChar(args []coretypes.Object, index int) coretypes.Char {
	obj := args[index]
	if c, yes := obj.(coretypes.Char); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Char", index))
}

func EnsureObjectIsString(obj coretypes.Object, pattern string) coretypes.String {
	if c, yes := obj.(coretypes.String); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.String", pattern))
}

func EnsureArgIsString(args []coretypes.Object, index int) coretypes.String {
	obj := args[index]
	if c, yes := obj.(coretypes.String); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.String", index))
}

func EnsureObjectIsSymbol(obj coretypes.Object, pattern string) Symbol {
	if c, yes := obj.(Symbol); yes {
		return c
	}
	panic(FailObject(obj, "Symbol", pattern))
}

func EnsureArgIsSymbol(args []coretypes.Object, index int) Symbol {
	obj := args[index]
	if c, yes := obj.(Symbol); yes {
		return c
	}
	panic(FailArg(obj, "Symbol", index))
}

func EnsureObjectIsKeyword(obj coretypes.Object, pattern string) Keyword {
	if c, yes := obj.(Keyword); yes {
		return c
	}
	panic(FailObject(obj, "Keyword", pattern))
}

func EnsureArgIsKeyword(args []coretypes.Object, index int) Keyword {
	obj := args[index]
	if c, yes := obj.(Keyword); yes {
		return c
	}
	panic(FailArg(obj, "Keyword", index))
}

func EnsureObjectIsRegex(obj coretypes.Object, pattern string) *coretypes.Regex {
	if c, yes := obj.(*coretypes.Regex); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Regex", pattern))
}

func EnsureArgIsRegex(args []coretypes.Object, index int) *coretypes.Regex {
	obj := args[index]
	if c, yes := obj.(*coretypes.Regex); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Regex", index))
}

func EnsureObjectIsBoolean(obj coretypes.Object, pattern string) coretypes.Boolean {
	if c, yes := obj.(coretypes.Boolean); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Boolean", pattern))
}

func EnsureArgIsBoolean(args []coretypes.Object, index int) coretypes.Boolean {
	obj := args[index]
	if c, yes := obj.(coretypes.Boolean); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Boolean", index))
}

func EnsureObjectIsTime(obj coretypes.Object, pattern string) coretypes.Time {
	if c, yes := obj.(coretypes.Time); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Time", pattern))
}

func EnsureArgIsTime(args []coretypes.Object, index int) coretypes.Time {
	obj := args[index]
	if c, yes := obj.(coretypes.Time); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Time", index))
}

func EnsureObjectIsNumber(obj coretypes.Object, pattern string) coretypes.Number {
	if c, yes := obj.(coretypes.Number); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Number", pattern))
}

func EnsureArgIsNumber(args []coretypes.Object, index int) coretypes.Number {
	obj := args[index]
	if c, yes := obj.(coretypes.Number); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Number", index))
}

func EnsureObjectIsSeqable(obj coretypes.Object, pattern string) Seqable {
	if c, yes := obj.(Seqable); yes {
		return c
	}
	panic(FailObject(obj, "Seqable", pattern))
}

func EnsureArgIsSeqable(args []coretypes.Object, index int) Seqable {
	obj := args[index]
	if c, yes := obj.(Seqable); yes {
		return c
	}
	panic(FailArg(obj, "Seqable", index))
}

func EnsureObjectIsCallable(obj coretypes.Object, pattern string) coretypes.Callable {
	if c, yes := obj.(coretypes.Callable); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Callable", pattern))
}

func EnsureArgIsCallable(args []coretypes.Object, index int) coretypes.Callable {
	obj := args[index]
	if c, yes := obj.(coretypes.Callable); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Callable", index))
}

func EnsureObjectIsType(obj coretypes.Object, pattern string) *coretypes.Type {
	if c, yes := obj.(*coretypes.Type); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Type", pattern))
}

func EnsureArgIsType(args []coretypes.Object, index int) *coretypes.Type {
	obj := args[index]
	if c, yes := obj.(*coretypes.Type); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Type", index))
}

func EnsureObjectIsMeta(obj coretypes.Object, pattern string) Meta {
	if c, yes := obj.(Meta); yes {
		return c
	}
	panic(FailObject(obj, "Meta", pattern))
}

func EnsureArgIsMeta(args []coretypes.Object, index int) Meta {
	obj := args[index]
	if c, yes := obj.(Meta); yes {
		return c
	}
	panic(FailArg(obj, "Meta", index))
}

func EnsureObjectIsInt(obj coretypes.Object, pattern string) coretypes.Int {
	if c, yes := obj.(coretypes.Int); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Int", pattern))
}

func EnsureArgIsInt(args []coretypes.Object, index int) coretypes.Int {
	obj := args[index]
	if c, yes := obj.(coretypes.Int); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Int", index))
}

func EnsureObjectIsDouble(obj coretypes.Object, pattern string) coretypes.Double {
	if c, yes := obj.(coretypes.Double); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Double", pattern))
}

func EnsureArgIsDouble(args []coretypes.Object, index int) coretypes.Double {
	obj := args[index]
	if c, yes := obj.(coretypes.Double); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Double", index))
}

func EnsureObjectIsStack(obj coretypes.Object, pattern string) coretypes.Stack {
	if c, yes := obj.(coretypes.Stack); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Stack", pattern))
}

func EnsureArgIsStack(args []coretypes.Object, index int) coretypes.Stack {
	obj := args[index]
	if c, yes := obj.(coretypes.Stack); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Stack", index))
}

func EnsureObjectIsMap(obj coretypes.Object, pattern string) Map {
	if c, yes := obj.(Map); yes {
		return c
	}
	panic(FailObject(obj, "Map", pattern))
}

func EnsureArgIsMap(args []coretypes.Object, index int) Map {
	obj := args[index]
	if c, yes := obj.(Map); yes {
		return c
	}
	panic(FailArg(obj, "Map", index))
}

func EnsureObjectIsSet(obj coretypes.Object, pattern string) Set {
	if c, yes := obj.(Set); yes {
		return c
	}
	panic(FailObject(obj, "Set", pattern))
}

func EnsureArgIsSet(args []coretypes.Object, index int) Set {
	obj := args[index]
	if c, yes := obj.(Set); yes {
		return c
	}
	panic(FailArg(obj, "Set", index))
}

func EnsureObjectIsAssociative(obj coretypes.Object, pattern string) Associative {
	if c, yes := obj.(Associative); yes {
		return c
	}
	panic(FailObject(obj, "Associative", pattern))
}

func EnsureArgIsAssociative(args []coretypes.Object, index int) Associative {
	obj := args[index]
	if c, yes := obj.(Associative); yes {
		return c
	}
	panic(FailArg(obj, "Associative", index))
}

func EnsureObjectIsReversible(obj coretypes.Object, pattern string) Reversible {
	if c, yes := obj.(Reversible); yes {
		return c
	}
	panic(FailObject(obj, "Reversible", pattern))
}

func EnsureArgIsReversible(args []coretypes.Object, index int) Reversible {
	obj := args[index]
	if c, yes := obj.(Reversible); yes {
		return c
	}
	panic(FailArg(obj, "Reversible", index))
}

func EnsureObjectIsNamed(obj coretypes.Object, pattern string) coretypes.Named {
	if c, yes := obj.(coretypes.Named); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Named", pattern))
}

func EnsureArgIsNamed(args []coretypes.Object, index int) coretypes.Named {
	obj := args[index]
	if c, yes := obj.(coretypes.Named); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Named", index))
}

func EnsureObjectIsComparator(obj coretypes.Object, pattern string) coretypes.Comparator {
	if c, yes := obj.(coretypes.Comparator); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Comparator", pattern))
}

func EnsureArgIsComparator(args []coretypes.Object, index int) coretypes.Comparator {
	obj := args[index]
	if c, yes := obj.(coretypes.Comparator); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Comparator", index))
}

func EnsureObjectIsRatio(obj coretypes.Object, pattern string) *coretypes.Ratio {
	if c, yes := obj.(*coretypes.Ratio); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Ratio", pattern))
}

func EnsureArgIsRatio(args []coretypes.Object, index int) *coretypes.Ratio {
	obj := args[index]
	if c, yes := obj.(*coretypes.Ratio); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Ratio", index))
}

func EnsureObjectIsBigFloat(obj coretypes.Object, pattern string) *coretypes.BigFloat {
	if c, yes := obj.(*coretypes.BigFloat); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.BigFloat", pattern))
}

func EnsureArgIsBigFloat(args []coretypes.Object, index int) *coretypes.BigFloat {
	obj := args[index]
	if c, yes := obj.(*coretypes.BigFloat); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.BigFloat", index))
}

func EnsureObjectIsBigInt(obj coretypes.Object, pattern string) *coretypes.BigInt {
	if c, yes := obj.(*coretypes.BigInt); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.BigInt", pattern))
}

func EnsureArgIsBigInt(args []coretypes.Object, index int) *coretypes.BigInt {
	obj := args[index]
	if c, yes := obj.(*coretypes.BigInt); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.BigInt", index))
}

func EnsureObjectIsNamespace(obj coretypes.Object, pattern string) *Namespace {
	if c, yes := obj.(*Namespace); yes {
		return c
	}
	panic(FailObject(obj, "Namespace", pattern))
}

func EnsureArgIsNamespace(args []coretypes.Object, index int) *Namespace {
	obj := args[index]
	if c, yes := obj.(*Namespace); yes {
		return c
	}
	panic(FailArg(obj, "Namespace", index))
}

func EnsureObjectIsVar(obj coretypes.Object, pattern string) *Var {
	if c, yes := obj.(*Var); yes {
		return c
	}
	panic(FailObject(obj, "Var", pattern))
}

func EnsureArgIsVar(args []coretypes.Object, index int) *Var {
	obj := args[index]
	if c, yes := obj.(*Var); yes {
		return c
	}
	panic(FailArg(obj, "Var", index))
}

func EnsureObjectIsError(obj coretypes.Object, pattern string) coretypes.Error {
	if c, yes := obj.(coretypes.Error); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Error", pattern))
}

func EnsureArgIsError(args []coretypes.Object, index int) coretypes.Error {
	obj := args[index]
	if c, yes := obj.(coretypes.Error); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Error", index))
}

func EnsureObjectIsFn(obj coretypes.Object, pattern string) *Fn {
	if c, yes := obj.(*Fn); yes {
		return c
	}
	panic(FailObject(obj, "Fn", pattern))
}

func EnsureArgIsFn(args []coretypes.Object, index int) *Fn {
	obj := args[index]
	if c, yes := obj.(*Fn); yes {
		return c
	}
	panic(FailArg(obj, "Fn", index))
}

func EnsureObjectIsDeref(obj coretypes.Object, pattern string) coretypes.Deref {
	if c, yes := obj.(coretypes.Deref); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Deref", pattern))
}

func EnsureArgIsDeref(args []coretypes.Object, index int) coretypes.Deref {
	obj := args[index]
	if c, yes := obj.(coretypes.Deref); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Deref", index))
}

func EnsureObjectIsAtom(obj coretypes.Object, pattern string) *Atom {
	if c, yes := obj.(*Atom); yes {
		return c
	}
	panic(FailObject(obj, "Atom", pattern))
}

func EnsureArgIsAtom(args []coretypes.Object, index int) *Atom {
	obj := args[index]
	if c, yes := obj.(*Atom); yes {
		return c
	}
	panic(FailArg(obj, "Atom", index))
}

func EnsureObjectIsRef(obj coretypes.Object, pattern string) Ref {
	if c, yes := obj.(Ref); yes {
		return c
	}
	panic(FailObject(obj, "Ref", pattern))
}

func EnsureArgIsRef(args []coretypes.Object, index int) Ref {
	obj := args[index]
	if c, yes := obj.(Ref); yes {
		return c
	}
	panic(FailArg(obj, "Ref", index))
}

func EnsureObjectIsKVReduce(obj coretypes.Object, pattern string) coretypes.KVReduce {
	if c, yes := obj.(coretypes.KVReduce); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.KVReduce", pattern))
}

func EnsureArgIsKVReduce(args []coretypes.Object, index int) coretypes.KVReduce {
	obj := args[index]
	if c, yes := obj.(coretypes.KVReduce); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.KVReduce", index))
}

func EnsureObjectIsReduce(obj coretypes.Object, pattern string) coretypes.Reduce {
	if c, yes := obj.(coretypes.Reduce); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Reduce", pattern))
}

func EnsureArgIsReduce(args []coretypes.Object, index int) coretypes.Reduce {
	obj := args[index]
	if c, yes := obj.(coretypes.Reduce); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Reduce", index))
}

func EnsureObjectIsPending(obj coretypes.Object, pattern string) coretypes.Pending {
	if c, yes := obj.(coretypes.Pending); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.Pending", pattern))
}

func EnsureArgIsPending(args []coretypes.Object, index int) coretypes.Pending {
	obj := args[index]
	if c, yes := obj.(coretypes.Pending); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.Pending", index))
}

func EnsureObjectIsFile(obj coretypes.Object, pattern string) *File {
	if c, yes := obj.(*File); yes {
		return c
	}
	panic(FailObject(obj, "File", pattern))
}

func EnsureArgIsFile(args []coretypes.Object, index int) *File {
	obj := args[index]
	if c, yes := obj.(*File); yes {
		return c
	}
	panic(FailArg(obj, "File", index))
}

func EnsureObjectIsio_Reader(obj coretypes.Object, pattern string) io.Reader {
	if c, yes := obj.(io.Reader); yes {
		return c
	}
	panic(FailObject(obj, "io.Reader", pattern))
}

func EnsureArgIsio_Reader(args []coretypes.Object, index int) io.Reader {
	obj := args[index]
	if c, yes := obj.(io.Reader); yes {
		return c
	}
	panic(FailArg(obj, "io.Reader", index))
}

func EnsureObjectIsio_Writer(obj coretypes.Object, pattern string) io.Writer {
	if c, yes := obj.(io.Writer); yes {
		return c
	}
	panic(FailObject(obj, "io.Writer", pattern))
}

func EnsureArgIsio_Writer(args []coretypes.Object, index int) io.Writer {
	obj := args[index]
	if c, yes := obj.(io.Writer); yes {
		return c
	}
	panic(FailArg(obj, "io.Writer", index))
}

func EnsureObjectIsStringReader(obj coretypes.Object, pattern string) coretypes.StringReader {
	if c, yes := obj.(coretypes.StringReader); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.StringReader", pattern))
}

func EnsureArgIsStringReader(args []coretypes.Object, index int) coretypes.StringReader {
	obj := args[index]
	if c, yes := obj.(coretypes.StringReader); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.StringReader", index))
}

func EnsureObjectIsio_RuneReader(obj coretypes.Object, pattern string) io.RuneReader {
	if c, yes := obj.(io.RuneReader); yes {
		return c
	}
	panic(FailObject(obj, "io.RuneReader", pattern))
}

func EnsureArgIsio_RuneReader(args []coretypes.Object, index int) io.RuneReader {
	obj := args[index]
	if c, yes := obj.(io.RuneReader); yes {
		return c
	}
	panic(FailArg(obj, "io.RuneReader", index))
}

func EnsureObjectIsChannel(obj coretypes.Object, pattern string) *Channel {
	if c, yes := obj.(*Channel); yes {
		return c
	}
	panic(FailObject(obj, "Channel", pattern))
}

func EnsureArgIsChannel(args []coretypes.Object, index int) *Channel {
	obj := args[index]
	if c, yes := obj.(*Channel); yes {
		return c
	}
	panic(FailArg(obj, "Channel", index))
}

func EnsureObjectIsCountedIndexed(obj coretypes.Object, pattern string) coretypes.CountedIndexed {
	if c, yes := obj.(coretypes.CountedIndexed); yes {
		return c
	}
	panic(FailObject(obj, "coretypes.CountedIndexed", pattern))
}

func EnsureArgIsCountedIndexed(args []coretypes.Object, index int) coretypes.CountedIndexed {
	obj := args[index]
	if c, yes := obj.(coretypes.CountedIndexed); yes {
		return c
	}
	panic(FailArg(obj, "coretypes.CountedIndexed", index))
}
