// This file is generated by generate-std.joke script. Do not edit manually!

package io

import (
	"fmt"
	"os"

	. "github.com/rcarmo/go-joker/core"
	coretypes "github.com/rcarmo/go-joker/core/types"
	corecollections "github.com/rcarmo/go-joker/core/types/collections"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of io.InternsOrThunks().")
	}
	ioNamespace.ResetMeta(MakeMeta(nil, `Provides basic interfaces to I/O primitives.`, "1.0"))

	ioNamespace.InternVar("close", close_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "f"))),
			`Closes f (IOWriter, IOReader, or File) if possible. Otherwise throws an error.`, "1.0"))

	ioNamespace.InternVar("copy", copy_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "dst"), coretypes.MakeSymbol(STRINGS.Intern, "src"))),
			`Copies from src to dst until either EOF is reached on src or an error occurs.
  Returns the number of bytes copied as an Int, or BigInt if the count exceeds the native int range.
  src must be IOReader, e.g. as returned by joker.os/open.
  dst must be IOWriter, e.g. as returned by joker.os/create.`, "1.0"))

	ioNamespace.InternVar("pipe", pipe_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom()),
			`Pipe creates a synchronous in-memory pipe. It can be used to connect code expecting an IOReader
  with code expecting an IOWriter.
  Returns a vector [reader, writer].`, "1.0"))

	ioNamespace.InternVar("read", read_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "r"), coretypes.MakeSymbol(STRINGS.Intern, "n"))),
			`Reads up to n bytes from IOReader r and returns a string of the read bytes.
  May return a shorter (or blank) string if EOF is encountered.`, "1.3.6").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

}
