// This file is generated by generate-std.joke script. Do not edit manually!

//go:build gen_code
// +build gen_code

package string

import (
	"fmt"
	"os"

	. "github.com/rcarmo/go-joker/core"
	coretypes "github.com/rcarmo/go-joker/core/types"
	corecollections "github.com/rcarmo/go-joker/core/types/collections"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of string.InternsOrThunks().")
	}
	stringNamespace.ResetMeta(MakeMeta(nil, `Implements simple functions to manipulate strings.`, "1.0"))

	stringNamespace.InternVar("blank?", isblank_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`True if s is nil, empty, or contains only whitespace.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "Boolean"}))

	stringNamespace.InternVar("capitalize", capitalize_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Converts first character of the string to upper-case, all other
  characters to lower-case.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("ends-with?", isends_with_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "substr"))),
			`True if s ends with substr.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "Boolean"}))

	stringNamespace.InternVar("escape", escape_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "cmap"))),
			`Return a new string, using cmap to escape each character ch
  from s as follows:

  If (cmap ch) is nil, append ch to the new string.
  If (cmap ch) is non-nil, append (str (cmap ch)) instead.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("includes?", isincludes_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "substr"))),
			`True if s includes substr.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "Boolean"}))

	stringNamespace.InternVar("index-of", index_of_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "value")), corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "value"), coretypes.MakeSymbol(STRINGS.Intern, "from"))),
			`Return index of value (string or char) in s, optionally searching
  forward from from or nil if not found.`, "1.0"))

	stringNamespace.InternVar("join", join_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "coll")), corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "separator"), coretypes.MakeSymbol(STRINGS.Intern, "coll"))),
			`Returns a string of all elements in coll, as returned by (seq coll), separated by an optional separator.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("last-index-of", last_index_of_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "value")), corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "value"), coretypes.MakeSymbol(STRINGS.Intern, "from"))),
			`Return last index of value (string or char) in s, optionally
  searching backward from from or nil if not found.`, "1.0"))

	stringNamespace.InternVar("lower-case", lower_case_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Converts string to all lower-case.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("pad-left", pad_left_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "pad"), coretypes.MakeSymbol(STRINGS.Intern, "n"))),
			`Returns s padded with pad at the beginning to length n.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("pad-right", pad_right_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "pad"), coretypes.MakeSymbol(STRINGS.Intern, "n"))),
			`Returns s padded with pad at the end to length n.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("re-quote", re_quote_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Returns an instance of Regex that matches the string exactly`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "Regex"}))

	stringNamespace.InternVar("replace", replace_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "match"), coretypes.MakeSymbol(STRINGS.Intern, "repl"))),
			`Replaces all instances of match (coretypes.String or Regex) with string repl in string s.

  If match is Regex, $1, $2, etc. in the replacement string repl are
  substituted with the string that matched the corresponding
  parenthesized group in the pattern.
  `, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("replace-first", replace_first_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "match"), coretypes.MakeSymbol(STRINGS.Intern, "repl"))),
			`Replaces the first instance of match (coretypes.String or Regex) with string repl in string s.

  If match is Regex, $1, $2, etc. in the replacement string repl are
  substituted with the string that matched the corresponding
  parenthesized group in the pattern.
  `, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("reverse", reverse_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Returns s with its characters reversed.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("split", split_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "sep")), corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "sep"), coretypes.MakeSymbol(STRINGS.Intern, "n"))),
			`Splits string on a string or regular expression. Returns vector of the splits.

  No more than n elements will be returned in the vector; the last element will
  be the unsplit remainder. If n is <= 0, no limit is in effect (all substrings
  are returned in the vector).`, "1.0"))

	stringNamespace.InternVar("split-lines", split_lines_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Splits string on \n or \r\n. Returns vector of the splits.`, "1.0"))

	stringNamespace.InternVar("starts-with?", isstarts_with_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"), coretypes.MakeSymbol(STRINGS.Intern, "substr"))),
			`True if s starts with substr.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "Boolean"}))

	stringNamespace.InternVar("trim", trim_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Removes whitespace from both ends of string.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("trim-left", trim_left_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Removes whitespace from the left side of string.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("trim-newline", trim_newline_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Removes all trailing newline \n or return \r characters from string.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("trim-right", trim_right_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Removes whitespace from the right side of string.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("triml", triml_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Removes whitespace from the left side of string.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("trimr", trimr_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Removes whitespace from the right side of string.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

	stringNamespace.InternVar("upper-case", upper_case_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom(coretypes.MakeSymbol(STRINGS.Intern, "s"))),
			`Converts string to all upper-case.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

}
