// This file is generated by generate-std.joke script. Do not edit manually!

package uuid

import (
	"fmt"
	"os"

	. "github.com/rcarmo/go-joker/core"
	coretypes "github.com/rcarmo/go-joker/core/types"
	corecollections "github.com/rcarmo/go-joker/core/types/collections"
)

func InternsOrThunks() {
	if VerbosityLevel > 0 {
		fmt.Fprintln(os.Stderr, "Lazily running slow version of uuid.InternsOrThunks().")
	}
	uuidNamespace.ResetMeta(MakeMeta(nil, `Generates UUIDs.`, "1.0"))

	uuidNamespace.InternVar("new", new_,
		MakeMeta(
			corecollections.NewListFrom(corecollections.NewVectorFrom()),
			`Creates a new random UUID.`, "1.0").Plus(coretypes.MakeKeyword(STRINGS.Intern, "tag"), coretypes.String{S: "coretypes.String"}))

}
