// This file is generated by generate-std.joke script. Do not edit manually!

package uuid

import (
	. "github.com/rcarmo/go-joker/core"
	coretypes "github.com/rcarmo/go-joker/core/types"
)

var __new__P ProcFn = __new_
var new_ Proc = Proc{Fn: __new__P, Name: "new_", Package: "std/uuid"}

func __new_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 0:
		_res := new()
		return coretypes.MakeString(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var uuidNamespace = GLOBAL_ENV.EnsureSymbolIsLib(coretypes.MakeSymbol(STRINGS.Intern, "joker.uuid"))

func init() {
	uuidNamespace.Lazy = Init
}
