// This file is generated by generate-std.joke script. Do not edit manually!

package markdown

import (
	. "github.com/rcarmo/go-joker/core"
	coretypes "github.com/rcarmo/go-joker/core/types"
)

var __convert_string__P ProcFn = __convert_string_
var convert_string_ Proc = Proc{Fn: __convert_string__P, Name: "convert_string_", Package: "std/markdown"}

func __convert_string_(_args []coretypes.Object) coretypes.Object {
	_c := len(_args)
	switch {
	case _c == 1:
		s := ExtractString(_args, 0)
		_res := convertString(s)
		return coretypes.MakeString(_res)

	case _c == 2:
		s := ExtractString(_args, 0)
		opts := ExtractMap(_args, 1)
		_res := convertStringOpts(s, opts)
		return coretypes.MakeString(_res)

	default:
		PanicArity(_c)
	}
	return NIL
}

func Init() {

	InternsOrThunks()
}

var markdownNamespace = GLOBAL_ENV.EnsureSymbolIsLib(coretypes.MakeSymbol(STRINGS.Intern, "joker.markdown"))

func init() {
	markdownNamespace.Lazy = Init
}
